### PR TITLE
Adds config file/error handling

### PR DESCRIPTION
**Pull request by SephirothSG**
Since you seem to be accepting pull requests now I figured I'd submit these changes again, not that I have any use for this project anymore but it might be useful for other people :)

### CODE REVIEW

**Comment by CodeBrauer** [comment]
I'll take a closer look at this.

**Comment by SephirothSG** [comment]
No worries, I added in a check to see if at least `1.ogg` exists and is readable to help prevent issues such as #14 and #13 popping up, perhaps this should be stricter in actually checking the filetype but meh.

**Comment by SephirothSG** [comment]
Any updates on this @CodeBrauer

**Comment by CodeBrauer** [comment]
I will check this asap, currently have to much projects at work for this :)

**Comment by SephirothSG** [comment]
Guess this is dead in the water, also noticed a minor mistake I made. will commit fix in a sec.

**Comment by SephirothSG** [comment]
@CodeBrauer Any updates?

**Pull request closed without merging**
